(ns ^:figwheel-always hearhear.filters)

(defn strip-html-tags [content]
  (clojure.string/replace content #"<[^>]*>" ""))

(defn strip-punctuation [content]
  (clojure.string/replace content #"<[^>]*>" ""))

;; Filter super common words
(defn is-a-common-word? [word]
  (some #(= (clojure.string/lower-case word) %) [
              "the"
              "be"
              "to"
              "of"
              "and"
              "a"
              "in"
              "that"
              "have"
              "i"
              "it"
              "for"
              "not"
              "on"
              "with"
              "he"
              "as"
              "you"
              "do"
              "at"
              "this"
              "but"
              "his"
              "by"
              "from"
              "they"
              "we"
              "say"
              "her"
              "she"
              "or"
              "an"
              "will"
              "my"
              "one"
              "all"
              "would"
              "there"
              "their"
              "what"
              "so"
              "up"
              "out"
              "if"
              "about"
              "who"
              "get"
              "which"
              "go"
              "me"
              "when"
              "make"
              "can"
              "like"
              "time"
              "no"
              "just"
              "him"
              "know"
              "take"
              "people"
              "into"
              "year"
              "your"
              "good"
              "some"
              "could"
              "them"
              "see"
              "other"
              "than"
              "then"
              "now"
              "look"
              "only"
              "come"
              "its"
              "over"
              "think"
              "also"
              "back"
              "after"
              "use"
              "two"
              "how"
              "our"
              "work"
              "first"
              "well"
              "way"
              "even"
              "new"
              "want"
              "because"
              "any"
              "these"
              "give"
              "day"
              "most"
              "related"
              "was"
              "very"
              "is"
              "are"
              "were"
              "where"
              ]))
